### ISSUE TITLE
Cannot run rubywarrior on a fresh ubuntu environment that comes with a default ruby installation

### ISSUE THREAD

**Issue by SamuelToh** [ryanb/ruby-warrior#87]
tigerroar@ubuntu:~$ rubywarrior
Welcome to Ruby Warrior
/var/lib/gems/1.9.1/gems/rubywarrior-0.1.3/lib/ruby_warrior/profile.rb:31:in `load': incompatible marshal file format (can't be read) (TypeError)
        format version 4.8 required; 254.154 given
        from /var/lib/gems/1.9.1/gems/rubywarrior-0.1.3/lib/ruby_warrior/profile.rb:31:in `decode'
        from /var/lib/gems/1.9.1/gems/rubywarrior-0.1.3/lib/ruby_warrior/profile.rb:35:in `load'
        from /var/lib/gems/1.9.1/gems/rubywarrior-0.1.3/lib/ruby_warrior/game.rb:8:in `start'
        from /var/lib/gems/1.9.1/gems/rubywarrior-0.1.3/lib/ruby_warrior/runner.rb:17:in `run'
        from /var/lib/gems/1.9.1/gems/rubywarrior-0.1.3/bin/rubywarrior:5:in `<top (required)>'
        from /usr/local/bin/rubywarrior:23:in `load'
        from /usr/local/bin/rubywarrior:23:in `<main>'

Newbie here. This is reproducible on a new ubuntu installation env that doesn't have the full ruby package installed yet. 

To fix this, do=> "sudo apt-get install ruby-full"

**Comment by StevenCopeland** [comment]
I am having the same problem.... Have you figured out a solution?
